version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketone_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - ticketone

  webserver:
    image: nginx:alpine
    container_name: ticketone_web
    ports:
      - "8010:80"
    restart: always
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - ticketone

  db:
    image: mysql:8.0
    container_name: ticketone_db
    restart: always
    environment:
      MYSQL_DATABASE: helpdesk_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ticketone

volumes:
  dbdata:

networks:
  ticketone: